MODULE AWG_Cloud_Mask_Tests
!$Id: awg_cloud_mask_tests.f90,v 1.5 2010/03/25 16:49:58 wstraka Exp $
!
!--- module use statements
!
USE CONSTANTS

IMPLICIT NONE

PRIVATE

PUBLIC:: RUT_ROUTINE
PUBLIC:: TUT_ROUTINE
PUBLIC:: RTCT_ROUTINE
PUBLIC:: ETROP_ROUTINE
PUBLIC:: PFMFT_ROUTINE
PUBLIC:: NFMFT_ROUTINE
PUBLIC:: RFMFT_ROUTINE
PUBLIC:: SET_CMASK_THRESHOLDS
PRIVATE:: SPLIT_WIN_CIRRUS_ROUTINE
PRIVATE:: TEMPIR_ROUTINE
PUBLIC:: RGCT_ROUTINE
PUBLIC:: RVCT_ROUTINE
PUBLIC:: NIRREF_Chn5_ROUTINE
PRIVATE:: NIRREF_Chn7_ROUTINE
PRIVATE:: CIRREF_ROUTINE
PRIVATE:: MECIDA_ROUTINE
PUBLIC:: EMISS4_ROUTINE
PUBLIC:: ULST_ROUTINE
PRIVATE:: ATMOSPHERIC_SCATTERING_CHN2

include 'awg_cloud_mask_tests_thresholds.inc'

CONTAINS

include 'awg_cloud_mask_tests_code.inc'



END MODULE AWG_Cloud_Mask_Tests
