!$Id$
!---------------------------------------------------------------------
! UNIVERSAL_CLOUD_TYPE include file #1 : CLAVR-x specific variables
!----------------------------------------------------------------------
  integer(kind=INT4), PRIVATE, PARAMETER :: Chan_Idx_16um = 6    !channel number for 1.6 micron
  integer(kind=INT4), PRIVATE, PARAMETER :: Chan_Idx_375um = 20  !channel number for 3.75 micron
  integer(kind=INT4), PRIVATE, PARAMETER :: Chan_Idx_67um = 27   !channel number for 6.7 micron
  integer(kind=INT4), PRIVATE, PARAMETER :: Chan_Idx_73um = 28   !channel number for 7.3 micron
  integer(kind=INT4), PRIVATE, PARAMETER :: Chan_Idx_85um = 29   !channel number for 8.5 micron
  integer(kind=INT4), PRIVATE, PARAMETER :: Chan_Idx_11um = 31   !channel number for 11 micron
  integer(kind=INT4), PRIVATE, PARAMETER :: Chan_Idx_12um = 32   !channel number for 12 micron
  integer(kind=INT4), PRIVATE, PARAMETER :: Chan_Idx_133um = 33  !channel number for 13.3 micron
