!$Id: akh_cloud_type_gsip_include_1.inc,v 1.1 2013/09/12 18:23:59 wstraka Exp $
!---------------------------------------------------------------------
! UNIVERSAL_CLOUD_TYPE include file #1 : CLAVR-x specific variables
!----------------------------------------------------------------------
  integer(kind=INT4), PRIVATE, PARAMETER :: Chan_Idx_375um = 7  !channel number for 3.75 micron
  integer(kind=INT4), PRIVATE, PARAMETER :: Chan_Idx_67um = 9   !channel number for 6.7 micron
  integer(kind=INT4), PRIVATE, PARAMETER :: Chan_Idx_73um = 28   !channel number for 7.3 micron
  integer(kind=INT4), PRIVATE, PARAMETER :: Chan_Idx_85um = 11   !channel number for 8.5 micron
  integer(kind=INT4), PRIVATE, PARAMETER :: Chan_Idx_11um = 14   !channel number for 11 micron
  integer(kind=INT4), PRIVATE, PARAMETER :: Chan_Idx_12um = 15   !channel number for 12 micron
  integer(kind=INT4), PRIVATE, PARAMETER :: Chan_Idx_133um = 16  !channel number for 13.3 micron
