!$Id: awg_cloud_mask_tests.f90,v 1.12.2.2 2014/01/26 04:48:31 heidinger Exp $
!--------------------------------------------------------------------------------------
! Clouds from AVHRR Extended (CLAVR-x) 1b PROCESSING SOFTWARE Version 5.3
!
! NAME: awg_cloud_mask_tests.f90 (src)
!       AWG_Cloud_Mask_Tests (program)
!
! PURPOSE: module use statements
!
! DESCRIPTION: 
!
! AUTHORS:
!  Andrew Heidinger, Andrew.Heidinger@noaa.gov
!  Andi Walther, CIMSS, andi.walther@ssec.wisc.edu
!  Denis Botambekov, CIMSS, denis.botambekov@ssec.wisc.edu
!  William Straka, CIMSS, wstraka@ssec.wisc.edu
!
! COPYRIGHT
! THIS SOFTWARE AND ITS DOCUMENTATION ARE CONSIDERED TO BE IN THE PUBLIC
! DOMAIN AND THUS ARE AVAILABLE FOR UNRESTRICTED PUBLIC USE. THEY ARE
! FURNISHED "AS IS." THE AUTHORS, THE UNITED STATES GOVERNMENT, ITS
! INSTRUMENTALITIES, OFFICERS, EMPLOYEES, AND AGENTS MAKE NO WARRANTY,
! EXPRESS OR IMPLIED, AS TO THE USEFULNESS OF THE SOFTWARE AND
! DOCUMENTATION FOR ANY PURPOSE. THEY ASSUME NO RESPONSIBILITY (1) FOR
! THE USE OF THE SOFTWARE AND DOCUMENTATION; OR (2) TO PROVIDE TECHNICAL
! SUPPORT TO USERS.
!
! PRIVATE ROUTINES:
!   SPLIT_WIN_CIRRUS_ROUTINE
!   TEMPIR_ROUTINE
!   CIRREF_ROUTINE
!   MECIDA_ROUTINE
!   ATMOSPHERIC_SCATTERING_CHN2
!
! PUBLIC ROUTINES:
!   RUT_ROUTINE
!   TUT_ROUTINE
!   RTCT_ROUTINE
!   ETROP_ROUTINE
!   PFMFT_ROUTINE
!   NFMFT_ROUTINE
!   RFMFT_ROUTINE
!   SET_CMASK_THRESHOLDS
!   RGCT_ROUTINE
!   RVCT_ROUTINE
!   NIRREF_Chn5_ROUTINE
!   NIRREF_Chn7_ROUTINE
!   EMISS4_ROUTINE
!   ULST_ROUTINE
!--------------------------------------------------------------------------------------
MODULE AWG_Cloud_Mask_Tests
!USE ALGORITHM_MODULE_USAGE
USE CONSTANTS

IMPLICIT NONE

PRIVATE

PUBLIC:: RUT_ROUTINE
PUBLIC:: TUT_ROUTINE
PUBLIC:: RTCT_ROUTINE
PUBLIC:: ETROP_ROUTINE
PUBLIC:: PFMFT_ROUTINE
PUBLIC:: NFMFT_ROUTINE
PUBLIC:: RFMFT_ROUTINE
PUBLIC:: SET_CMASK_THRESHOLDS
PRIVATE:: SPLIT_WIN_CIRRUS_ROUTINE
PRIVATE:: TEMPIR_ROUTINE
PUBLIC:: RGCT_ROUTINE
PUBLIC:: RVCT_ROUTINE
PUBLIC:: NIRREF_Chn5_ROUTINE
PUBLIC:: NIRREF_Chn7_ROUTINE
PUBLIC:: CIRREF_ROUTINE
PRIVATE:: MECIDA_ROUTINE
PUBLIC:: EMISS4_ROUTINE
PUBLIC:: ULST_ROUTINE
PUBLIC:: CIRH2O_ROUTINE
PRIVATE:: Term_Therm_Stab_Routine
PUBLIC:: Compute_NWC
!PRIVATE:: ATMOSPHERIC_SCATTERING_CHN2
PUBLIC:: Term_Refl_Norm_ACM
PUBLIC:: Compute_Clear_Sky_Scatter_ACM

include 'awg_cloud_mask_tests_thresholds.inc'

CONTAINS

include 'awg_cloud_mask_tests_code.inc'



END MODULE AWG_Cloud_Mask_Tests
